## Housing Kaggle Competition

#### Importing

In [65]:
import pandas as pd
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor

train_data_raw = pd.read_csv("train.csv", index_col='Id') 
test_data_raw = pd.read_csv("test.csv", index_col='Id')

In [66]:
train_data_raw

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [67]:
test_data_raw

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,Inside,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

#### Making Train and Valid X and y

In [68]:
test_data_raw.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1459 entries, 1461 to 2919
Data columns (total 79 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1459 non-null   int64
 1   MSZoning       1455 non-null   object
 2   LotFrontage    1232 non-null   float64
 3   LotArea        1459 non-null   int64
 4   Street         1459 non-null   object
 5   Alley          107 non-null    object
 6   LotShape       1459 non-null   object
 7   LandContour    1459 non-null   object
 8   Utilities      1457 non-null   object
 9   LotConfig      1459 non-null   object
 10  LandSlope      1459 non-null   object
 11  Neighborhood   1459 non-null   object
 12  Condition1     1459 non-null   object
 13  Condition2     1459 non-null   object
 14  BldgType       1459 non-null   object
 15  HouseStyle     1459 non-null   object
 16  OverallQual    1459 non-null   int64
 17  OverallCond    1459 non-null   int64
 18  YearBuilt      1459 non-null   int64
 19  YearRemodAdd   1459 non-null   int64
 20  RoofStyle      1459 non-null   object
 21  RoofMatl       1459 non-null   object
 22  Exterior1st    1458 non-null   object
 23  Exterior2nd    1458 non-null   object
 24  MasVnrType     1443 non-null   object
 25  MasVnrArea     1444 non-null   float64
 26  ExterQual      1459 non-null   object
 27  ExterCond      1459 non-null   object
 28  Foundation     1459 non-null   object
 29  BsmtQual       1415 non-null   object
 30  BsmtCond       1414 non-null   object
 31  BsmtExposure   1415 non-null   object
 32  BsmtFinType1   1417 non-null   object
 33  BsmtFinSF1     1458 non-null   float64
 34  BsmtFinType2   1417 non-null   object
 35  BsmtFinSF2     1458 non-null   float64
 36  BsmtUnfSF      1458 non-null   float64
 37  TotalBsmtSF    1458 non-null   float64
 38  Heating        1459 non-null   object
 39  HeatingQC      1459 non-null   object
 40  CentralAir     1459 non-null   object
 41  Electrical     1459 non-null   object
 42  1stFlrSF       1459 non-null   int64
 43  2ndFlrSF       1459 non-null   int64
 44  LowQualFinSF   1459 non-null   int64
 45  GrLivArea      1459 non-null   int64
 46  BsmtFullBath   1457 non-null   float64
 47  BsmtHalfBath   1457 non-null   float64
 48  FullBath       1459 non-null   int64
 49  HalfBath       1459 non-null   int64
 50  BedroomAbvGr   1459 non-null   int64
 51  KitchenAbvGr   1459 non-null   int64
 52  KitchenQual    1458 non-null   object
 53  TotRmsAbvGrd   1459 non-null   int64
 54  Functional     1457 non-null   object
 55  Fireplaces     1459 non-null   int64
 56  FireplaceQu    729 non-null    object
 57  GarageType     1383 non-null   object
 58  GarageYrBlt    1381 non-null   float64
 59  GarageFinish   1381 non-null   object
 60  GarageCars     1458 non-null   float64
 61  GarageArea     1458 non-null   float64
 62  GarageQual     1381 non-null   object
 63  GarageCond     1381 non-null   object
 64  PavedDrive     1459 non-null   object
 65  WoodDeckSF     1459 non-null   int64
 66  OpenPorchSF    1459 non-null   int64
 67  EnclosedPorch  1459 non-null   int64
 68  3SsnPorch      1459 non-null   int64
 69  ScreenPorch    1459 non-null   int64
 70  PoolArea       1459 non-null   int64
 71  PoolQC         3 non-null      object
 72  Fence          290 non-null    object
 73  MiscFeature    51 non-null     object
 74  MiscVal        1459 non-null   int64
 75  MoSold         1459 non-null   int64
 76  YrSold         1459 non-null   int64
 77  SaleType       1458 non-null   object
 78  SaleCondition  1459 non-null   object
dtypes: float64(11), int64(25), object(43)
memory usage: 911.9+ KB

combined dataframe concationat
find columns with nulls and then save those as a list and drop those from both

In [69]:
train_data = train_data_raw.select_dtypes(include='number')
test_data = test_data_raw.select_dtypes(include='number')
train_data.dtypes
test_data.dtypes

MSSubClass         int64
LotFrontage      float64
LotArea            int64
OverallQual        int64
OverallCond        int64
YearBuilt          int64
YearRemodAdd       int64
MasVnrArea       float64
BsmtFinSF1       float64
BsmtFinSF2       float64
BsmtUnfSF        float64
TotalBsmtSF      float64
1stFlrSF           int64
2ndFlrSF           int64
LowQualFinSF       int64
GrLivArea          int64
BsmtFullBath     float64
BsmtHalfBath     float64
FullBath           int64
HalfBath           int64
BedroomAbvGr       int64
KitchenAbvGr       int64
TotRmsAbvGrd       int64
Fireplaces         int64
GarageYrBlt      float64
GarageCars       float64
GarageArea       float64
WoodDeckSF         int64
OpenPorchSF        int64
EnclosedPorch      int64
3SsnPorch          int64
ScreenPorch        int64
PoolArea           int64
MiscVal            int64
MoSold             int64
YrSold             int64
dtype: object

In [70]:
con = pd.concat([train_data, test_data])
con.info()
nas = con.columns[con.isna().any()].tolist()
nas.remove('SalePrice')
nas

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 1 to 2919
Data columns (total 37 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     2919 non-null   int64
 1   LotFrontage    2433 non-null   float64
 2   LotArea        2919 non-null   int64
 3   OverallQual    2919 non-null   int64
 4   OverallCond    2919 non-null   int64
 5   YearBuilt      2919 non-null   int64
 6   YearRemodAdd   2919 non-null   int64
 7   MasVnrArea     2896 non-null   float64
 8   BsmtFinSF1     2918 non-null   float64
 9   BsmtFinSF2     2918 non-null   float64
 10  BsmtUnfSF      2918 non-null   float64
 11  TotalBsmtSF    2918 non-null   float64
 12  1stFlrSF       2919 non-null   int64
 13  2ndFlrSF       2919 non-null   int64
 14  LowQualFinSF   2919 non-null   int64
 15  GrLivArea      2919 non-null   int64
 16  BsmtFullBath   2917 non-null   float64
 17  BsmtHalfBath   2917 non-null   float64
 18  FullBath       2919 non-null   int64
 19  HalfBath       2919 non-null   int64
 20  BedroomAbvGr   2919 non-null   int64
 21  KitchenAbvGr   2919 non-null   int64
 22  TotRmsAbvGrd   2919 non-null   int64
 23  Fireplaces     2919 non-null   int64
 24  GarageYrBlt    2760 non-null   float64
 25  GarageCars     2918 non-null   float64
 26  GarageArea     2918 non-null   float64
 27  WoodDeckSF     2919 non-null   int64
 28  OpenPorchSF    2919 non-null   int64
 29  EnclosedPorch  2919 non-null   int64
 30  3SsnPorch      2919 non-null   int64
 31  ScreenPorch    2919 non-null   int64
 32  PoolArea       2919 non-null   int64
 33  MiscVal        2919 non-null   int64
 34  MoSold         2919 non-null   int64
 35  YrSold         2919 non-null   int64
 36  SalePrice      1460 non-null   float64
dtypes: float64(12), int64(25)
memory usage: 866.6 KB

['LotFrontage',
 'MasVnrArea',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 'BsmtFullBath',
 'BsmtHalfBath',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea']

In [71]:
#train_data

In [72]:
#test_data

In [73]:
train_data1 = train_data.drop(columns = nas)
test_data1 = test_data.drop(columns = nas)

In [74]:
#train_data

In [75]:
X = train_data1[list(train_data1.columns)]
X.drop(columns='SalePrice', inplace=True)
y = train_data.SalePrice

In [76]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 1 to 1460
Data columns (total 25 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   LotArea        1460 non-null   int64
 2   OverallQual    1460 non-null   int64
 3   OverallCond    1460 non-null   int64
 4   YearBuilt      1460 non-null   int64
 5   YearRemodAdd   1460 non-null   int64
 6   1stFlrSF       1460 non-null   int64
 7   2ndFlrSF       1460 non-null   int64
 8   LowQualFinSF   1460 non-null   int64
 9   GrLivArea      1460 non-null   int64
 10  FullBath       1460 non-null   int64
 11  HalfBath       1460 non-null   int64
 12  BedroomAbvGr   1460 non-null   int64
 13  KitchenAbvGr   1460 non-null   int64
 14  TotRmsAbvGrd   1460 non-null   int64
 15  Fireplaces     1460 non-null   int64
 16  WoodDeckSF     1460 non-null   int64
 17  OpenPorchSF    1460 non-null   int64
 18  EnclosedPorch  1460 non-null   int64
 19  3SsnPorch      1460 non-null   int64
 20  ScreenPorch    1460 non-null   int64
 21  PoolArea       1460 non-null   int64
 22  MiscVal        1460 non-null   int64
 23  MoSold         1460 non-null   int64
 24  YrSold         1460 non-null   int64
dtypes: int64(25)
memory usage: 296.6 KB

In [77]:
train_X, val_X, train_y, val_y = train_test_split(X, y, random_state=1)

In [88]:
val_predictions = home_model.predict(val_X)
val_mae = mean_absolute_error(val_predictions, val_y)
val_mae

25785.29589041096

In [89]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

forest_model = RandomForestRegressor(random_state=1)
forest_model.fit(train_X, train_y)
melb_preds = forest_model.predict(val_X)
print(mean_absolute_error(val_y, melb_preds))

17905.8978630137

In [90]:
final_model = RandomForestRegressor(random_state = 1)
final_model.fit(X,y)

RandomForestRegressor(random_state=1)

In [91]:
X.shape

(1460, 25)

In [82]:
test_data

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
Id,,,,,,,,,,,,,,,,,,,,,
1461,20,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,...,730.0,140,0,0,0,120,0,0,6,2010
1462,20,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,...,312.0,393,36,0,0,0,0,12500,6,2010
1463,60,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,...,482.0,212,34,0,0,0,0,0,3,2010
1464,60,78.0,9978,6,6,1998,1998,20.0,602.0,0.0,...,470.0,360,36,0,0,0,0,0,6,2010
1465,120,43.0,5005,8,5,1992,1992,0.0,263.0,0.0,...,506.0,0,82,0,0,144,0,0,1,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,160,21.0,1936,4,7,1970,1970,0.0,0.0,0.0,...,0.0,0,0,0,0,0,0,0,6,2006
2916,160,21.0,1894,4,5,1970,1970,0.0,252.0,0.0,...,286.0,0,24,0,0,0,0,0,4,2006
2917,20,160.0,20000,5,7,1960,1996,0.0,1224.0,0.0,...,576.0,474,0,0,0,0,0,0,9,2006
2918,85,62.0,10441,5,5,1992,1992,0.0,337.0,0.0,...,0.0,80,32,0,0,0,0,700,7,2006
2919,60,74.0,9627,7,5,1993,1994,94.0,758.0,0.0,...,650.0,190,48,0,0,0,0,0,11,2006

In [83]:
cols = list(train_data1.columns)
cols.remove('SalePrice')
cols

['MSSubClass',
 'LotArea',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold']

In [84]:
X_test = test_data[cols]

In [85]:
X_test

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,...,Fireplaces,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
Id,,,,,,,,,,,,,,,,,,,,,
1461,20,11622,5,6,1961,1961,896,0,0,896,...,0,140,0,0,0,120,0,0,6,2010
1462,20,14267,6,6,1958,1958,1329,0,0,1329,...,0,393,36,0,0,0,0,12500,6,2010
1463,60,13830,5,5,1997,1998,928,701,0,1629,...,1,212,34,0,0,0,0,0,3,2010
1464,60,9978,6,6,1998,1998,926,678,0,1604,...,1,360,36,0,0,0,0,0,6,2010
1465,120,5005,8,5,1992,1992,1280,0,0,1280,...,0,0,82,0,0,144,0,0,1,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,160,1936,4,7,1970,1970,546,546,0,1092,...,0,0,0,0,0,0,0,0,6,2006
2916,160,1894,4,5,1970,1970,546,546,0,1092,...,0,0,24,0,0,0,0,0,4,2006
2917,20,20000,5,7,1960,1996,1224,0,0,1224,...,1,474,0,0,0,0,0,0,9,2006
2918,85,10441,5,5,1992,1992,970,0,0,970,...,0,80,32,0,0,0,0,700,7,2006
2919,60,9627,7,5,1993,1994,996,1004,0,2000,...,1,190,48,0,0,0,0,0,11,2006

In [86]:
predictions = final_model.predict(X_test)
predictions

array([127456.16, 156361.  , 172348.25, ..., 155347.  , 130054.1 ,
       229014.75])

In [87]:
output = pd.DataFrame({'Id': test_data.index, 'SalePrice': predictions})

output.to_csv('submission3.csv', index=False)